// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pibjpeltpfqxicozdefd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBpYmpwZWx0cGZxeGljb3pkZWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2OTI0MzksImV4cCI6MjA2MjI2ODQzOX0.0Gop3gryWEBCM1iQAY_z-4FGaDNhQlITlFbfrBOmI-k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);